# Generated by Django 2.0.5 on 2018-05-04 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('PR', 'PR'), ('SR', 'SR')], default='PR', max_length=2)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('is_variation', models.BooleanField(default=False)),
                ('brand_id', models.IntegerField()),
                ('code', models.IntegerField(unique=True)),
                ('family', models.IntegerField()),
                ('is_complement', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_visibility', models.BooleanField(default=True)),
                ('price', models.FloatField()),
                ('price_offer', models.FloatField(null=True)),
                ('offer_day_from', models.DateTimeField(null=True)),
                ('offer_day_to', models.DateTimeField(null=True)),
                ('quantity', models.IntegerField()),
                ('sku', models.IntegerField(unique=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='products.Product')),
            ],
        ),
    ]
